# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "C:/Users/cosea/Documents/vivado/Pipelined/ProyectoFinal/ProyectoFinal.runs/synth_1/top.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param general.usePosixSpawnForFork 1
set_param synth.incrementalSynthesisCache C:/Users/cosea/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-25756-YIUSEPPE/incrSyn
set_param checkpoint.writeSynthRtdsInDcp 1
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/cosea/Documents/vivado/Pipelined/ProyectoFinal/ProyectoFinal.cache/wt [current_project]
set_property parent.project_path C:/Users/cosea/Documents/vivado/Pipelined/ProyectoFinal/ProyectoFinal.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part_repo_paths {C:/Users/cosea/AppData/Roaming/Xilinx/Vivado/2025.1/xhub/board_store/xilinx_board_store} [current_project]
set_property board_part digilentinc.com:basys3:part0:1.2 [current_project]
set_property ip_output_repo c:/Users/cosea/Documents/vivado/Pipelined/ProyectoFinal/ProyectoFinal.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_mem C:/Users/cosea/Documents/vivado/Pipelined/ProyectoFinal/ProyectoFinal.srcs/sources_1/new/riscvtest.txt
read_verilog -library xil_defaultlib {
  C:/Users/cosea/Documents/vivado/Pipelined/ProyectoFinal/ProyectoFinal.srcs/sources_1/new/divided/datapath/adder.v
  C:/Users/cosea/Documents/vivado/Pipelined/ProyectoFinal/ProyectoFinal.srcs/sources_1/new/divided/datapath/alu.v
  C:/Users/cosea/Documents/vivado/Pipelined/ProyectoFinal/ProyectoFinal.srcs/sources_1/new/divided/controller/aludec.v
  C:/Users/cosea/Documents/vivado/Pipelined/ProyectoFinal/ProyectoFinal.srcs/sources_1/new/divided/controller/controller.v
  C:/Users/cosea/Documents/vivado/Pipelined/ProyectoFinal/ProyectoFinal.srcs/sources_1/new/divided/datapath/datapath.v
  C:/Users/cosea/Documents/vivado/Pipelined/ProyectoFinal/ProyectoFinal.srcs/sources_1/new/divided/dmen.v
  C:/Users/cosea/Documents/vivado/Pipelined/ProyectoFinal/ProyectoFinal.srcs/sources_1/new/divided/datapath/extend.v
  C:/Users/cosea/Documents/vivado/Pipelined/ProyectoFinal/ProyectoFinal.srcs/sources_1/new/divided/flopr.v
  C:/Users/cosea/Documents/vivado/Pipelined/ProyectoFinal/ProyectoFinal.srcs/sources_1/new/divided/fp_modules/fp_regfile.v
  C:/Users/cosea/Documents/vivado/Pipelined/ProyectoFinal/ProyectoFinal.srcs/sources_1/new/divided/fp_modules/fpu_add_fp32_vivado.v
  C:/Users/cosea/Documents/vivado/Pipelined/ProyectoFinal/ProyectoFinal.srcs/sources_1/new/divided/fp_modules/fpu_dec.v
  C:/Users/cosea/Documents/vivado/Pipelined/ProyectoFinal/ProyectoFinal.srcs/sources_1/new/divided/fp_modules/fpu_div_fp32_vivado.v
  C:/Users/cosea/Documents/vivado/Pipelined/ProyectoFinal/ProyectoFinal.srcs/sources_1/new/divided/fp_modules/fpu_minmax_fp32_vivado.v
  C:/Users/cosea/Documents/vivado/Pipelined/ProyectoFinal/ProyectoFinal.srcs/sources_1/new/divided/fp_modules/fpu_mul_fp32_vivado.v
  C:/Users/cosea/Documents/vivado/Pipelined/ProyectoFinal/ProyectoFinal.srcs/sources_1/new/divided/fp_modules/fpu_top.v
  C:/Users/cosea/Documents/vivado/Pipelined/ProyectoFinal/ProyectoFinal.srcs/sources_1/new/divided/hazard/hazard_unit.v
  C:/Users/cosea/Documents/vivado/Pipelined/ProyectoFinal/ProyectoFinal.srcs/sources_1/new/divided/imen.v
  C:/Users/cosea/Documents/vivado/Pipelined/ProyectoFinal/ProyectoFinal.srcs/sources_1/new/divided/controller/maindec.v
  C:/Users/cosea/Documents/vivado/Pipelined/ProyectoFinal/ProyectoFinal.srcs/sources_1/new/mul2_vector_mul.v
  C:/Users/cosea/Documents/vivado/Pipelined/ProyectoFinal/ProyectoFinal.srcs/sources_1/new/mul_floating_points.v
  C:/Users/cosea/Documents/vivado/Pipelined/ProyectoFinal/ProyectoFinal.srcs/sources_1/new/divided/datapath/mux2.v
  C:/Users/cosea/Documents/vivado/Pipelined/ProyectoFinal/ProyectoFinal.srcs/sources_1/new/divided/datapath/mux3.v
  C:/Users/cosea/Documents/vivado/Pipelined/ProyectoFinal/ProyectoFinal.srcs/sources_1/new/divided/pipeline.v
  C:/Users/cosea/Documents/vivado/Pipelined/ProyectoFinal/ProyectoFinal.srcs/sources_1/new/divided/register_phases/reg_decode_to_execute.v
  C:/Users/cosea/Documents/vivado/Pipelined/ProyectoFinal/ProyectoFinal.srcs/sources_1/new/divided/register_phases/reg_decode_to_execute_control.v
  C:/Users/cosea/Documents/vivado/Pipelined/ProyectoFinal/ProyectoFinal.srcs/sources_1/new/divided/register_phases/reg_decode_to_execute_fp.v
  C:/Users/cosea/Documents/vivado/Pipelined/ProyectoFinal/ProyectoFinal.srcs/sources_1/new/divided/register_phases/reg_execute_to_memory.v
  C:/Users/cosea/Documents/vivado/Pipelined/ProyectoFinal/ProyectoFinal.srcs/sources_1/new/divided/register_phases/reg_execute_to_memory_control.v
  C:/Users/cosea/Documents/vivado/Pipelined/ProyectoFinal/ProyectoFinal.srcs/sources_1/new/divided/register_phases/reg_fetch_to_decode.v
  C:/Users/cosea/Documents/vivado/Pipelined/ProyectoFinal/ProyectoFinal.srcs/sources_1/new/reg_floating.v
  C:/Users/cosea/Documents/vivado/Pipelined/ProyectoFinal/ProyectoFinal.srcs/sources_1/new/divided/register_phases/reg_memory_to_writeback.v
  C:/Users/cosea/Documents/vivado/Pipelined/ProyectoFinal/ProyectoFinal.srcs/sources_1/new/divided/register_phases/reg_memory_to_writeback_control.v
  C:/Users/cosea/Documents/vivado/Pipelined/ProyectoFinal/ProyectoFinal.srcs/sources_1/new/divided/datapath/regfile.v
  C:/Users/cosea/Documents/vivado/Pipelined/ProyectoFinal/ProyectoFinal.srcs/sources_1/new/sum_floating_points.v
  C:/Users/cosea/Documents/vivado/Pipelined/ProyectoFinal/ProyectoFinal.srcs/sources_1/new/top.v
}
OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top top -part xc7a35tcpg236-1
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
generate_parallel_reports -reports { "report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb"  } 
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
